# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elf.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=elf.utils.random_name_upload_to)),
                ('intro', models.TextField(blank=True, max_length=200)),
                ('n_following', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('n_follower', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('interest', models.BooleanField()),
                ('n_review', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legolas.Area')),
                ('sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legolas.SubArea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
